vim.keymap.set("n", "<leader>nt", vim.cmd.NvimTreeToggle)
vim.keymap.set("n", "<leader>nf", vim.cmd.NvimTreeFocus)
vim.keymap.set("n", "<leader>nr", vim.cmd.NvimTreeRefresh)
vim.keymap.set("n", "<leader>nl", vim.cmd.NvimTreeFindFile)
vim.keymap.set("n", "<leader>nc", vim.cmd.NvimTreeCollapse)
